# config.yml
data:
  freq_threshold: 2
  batch_size: 128

model:
  enc_emb_dim: 256
  dec_emb_dim: 256
  enc_hid_dim: 512
  dec_hid_dim: 512
  enc_dropout: 0.5
  dec_dropout: 0.5

training:
  learning_rate: 0.001
  n_epochs: 10
  clip: 1.0
  teacher_forcing_ratio: 0.5