[tool.poetry]
name = "seq2seq-translation-assignment"
version = "0.1.0"
description = "Machine Translation Seq2Seq Implementation for Home Exercise 1"
authors = ["Bui Tran Duy Khang <dikhang@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
# Cho phép Poetry tự chọn numpy 1.x hoặc 2.x để tránh xung đột với Thinc/Spacy
numpy = "^1.26.0 || ^2.0.0"

# Spacy và model ngôn ngữ
spacy = "^3.7.4"

# Thư viện đọc config file .yml
PyYAML = "^6.0"

# Data Science & Vis
matplotlib = "^3.8.0"
jupyter = "^1.0.0"
notebook = "^7.0.0"
tqdm = "^4.66.0"

# PyTorch
torch = "^2.2.0"

# Đánh giá mô hình (thay thế torchtext)
sacrebleu = "^2.4.0"

[tool.poetry.group.dev.dependencies]
black = "^24.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"